version: '3.8'
services:
  face_recognition:
    image: face_recognition_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/config  # Montowanie folderu konfiguracyjnego
      - ./logs:/app/logs  # Montowanie logów 
    environment:
      - CONFIG_PATH=/config/config.yml
    restart: always
